server:
  port: 9091

spring:
  cloud:
    stream:
      default-binder: vinay-logics
      binders:
        vinay-logics:
          type: kafka
          environment:
            spring.cloud.stream.kafka.binder.autoCreateTopics: true
            spring.cloud.stream.kafka.binder.minPartitionCount: 10
            spring.cloud.stream.kafka.binder.brokers: 'localhost:9092'
